"""config string

Revision ID: 0ce49d185ab8
Revises: 1fc9b119289f
Create Date: 2025-07-06 21:10:30.877683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce49d185ab8'
down_revision: Union[str, Sequence[str], None] = '1fc9b119289f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_configs', sa.Column('config_string', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_configs', 'config_string')
    # ### end Alembic commands ###
