"""cascade deletion

Revision ID: 1fc9b119289f
Revises: f65388b2f748
Create Date: 2025-06-25 22:05:09.253013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc9b119289f'
down_revision: Union[str, Sequence[str], None] = 'f65388b2f748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_configs_server_id_fkey'), 'user_configs', type_='foreignkey')
    op.drop_constraint(op.f('user_configs_telegram_id_fkey'), 'user_configs', type_='foreignkey')
    op.create_foreign_key(None, 'user_configs', 'users', ['telegram_id'], ['telegram_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_configs', 'servers', ['server_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_keys_telegram_id_fkey'), 'user_keys', type_='foreignkey')
    op.create_foreign_key(None, 'user_keys', 'users', ['telegram_id'], ['telegram_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_keys', type_='foreignkey')
    op.create_foreign_key(op.f('user_keys_telegram_id_fkey'), 'user_keys', 'users', ['telegram_id'], ['telegram_id'])
    op.drop_constraint(None, 'user_configs', type_='foreignkey')
    op.drop_constraint(None, 'user_configs', type_='foreignkey')
    op.create_foreign_key(op.f('user_configs_telegram_id_fkey'), 'user_configs', 'users', ['telegram_id'], ['telegram_id'])
    op.create_foreign_key(op.f('user_configs_server_id_fkey'), 'user_configs', 'servers', ['server_id'], ['id'])
    # ### end Alembic commands ###
