"""default inbound field

Revision ID: 51d2addaca41
Revises: 068ea1688c8d
Create Date: 2025-06-22 13:38:47.217841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d2addaca41'
down_revision: Union[str, Sequence[str], None] = '068ea1688c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('default_inbound', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'default_inbound')
    # ### end Alembic commands ###
