"""expire date datetime to int

Revision ID: 6a261d6b2116
Revises: ff4dde7fe951
Create Date: 2025-06-22 14:47:54.720101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a261d6b2116'
down_revision: Union[str, Sequence[str], None] = 'ff4dde7fe951'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_configs',
        'expire_date',
        existing_type=sa.DateTime(),
        type_=sa.Integer(),
        postgresql_using="EXTRACT(EPOCH FROM expire_date)::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_configs',
        'expire_date',
        existing_type=sa.Integer(),
        type_=sa.DateTime(),
        postgresql_using="TO_TIMESTAMP(expire_date)"
    )
    # ### end Alembic commands ###
