"""Update key null tg id

Revision ID: 9af3d87b982f
Revises: b18513d2a2f8
Create Date: 2025-06-17 22:46:16.319804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af3d87b982f'
down_revision: Union[str, Sequence[str], None] = 'b18513d2a2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_keys', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_keys', 'telegram_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
