"""Add admin flag

Revision ID: b18513d2a2f8
Revises: ef7d42fd0512
Create Date: 2025-06-17 22:32:54.144118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18513d2a2f8'
down_revision: Union[str, Sequence[str], None] = 'ef7d42fd0512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_keys', ['key'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'user_keys', type_='unique')
    # ### end Alembic commands ###
