"""uuid id for configs

Revision ID: f65388b2f748
Revises: 6a261d6b2116
Create Date: 2025-06-22 20:18:53.401033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f65388b2f748'
down_revision: Union[str, Sequence[str], None] = '6a261d6b2116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_configs', sa.Column('id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_configs', 'id')
    # ### end Alembic commands ###
